apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sa.yaml
  - deployment.yaml
  - service.yaml
  - mapping.yaml
commonLabels:
  app: workspace-web
configMapGenerator:
- name: workspace-web-config
  literals:
  - PORT=8080
  - JS_MANIFEST_KEY='app.js'
  - BASE_PATH='/workspace/'
  - PAGE_TITLE='Workspace'
  - APP_CONTAINER_ID='app'
