apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base
nameSuffix: -production
commonLabels:
  environment: production
patchesStrategicMerge:
  - patch-mapping-service.yaml

